name: Run Meme Bot
on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install System Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-liberation
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Bot
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: python main.py
      - name: Update Logs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add posted.json || exit 0
          git commit -m "Automated log update [skip ci]" || exit 0
          git push
